# Generated by Django 4.2 on 2023-05-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_address',
            name='contact',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
